# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
    - name: Docker commands
      run: |
          docker login --username parteg132 --password ${{ secrets.DOCKER_PASS }}
          docker build . -t parteg132/catalog-api-image-actions
          docker image push parteg132/catalog-api-image-actions
    
    - name: Copying files
      run: |
          mkdir Artifacts
          cp -r bin Artifacts
          cp -r routes Artifacts
          cp app.js Artifacts
          cp package-lock.json Artifacts
          cp package.json Artifacts
        
    - name: Upload APP artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Artifacts #${{ env.APP_ARTIFACT_NAME }}
        path: Artifacts #${{ env.APP_PACKAGE_PATH }}
